dtb-$(CONFIG_SOC_EXYNOS9810) += \
    exynos9810-starlte_eur_open_16.dtb \
    exynos9810-starlte_eur_open_17.dtb \
    exynos9810-starlte_eur_open_18.dtb \
    exynos9810-starlte_eur_open_20.dtb \
    exynos9810-starlte_eur_open_23.dtb \
    exynos9810-starlte_eur_open_26.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
